#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
系统配置文件 - 集中管理所有配置项
"""
import os
from typing import Optional


class RedisConfig:
    """Redis 配置"""
    HOST: str = os.getenv("REDIS_HOST", "127.0.0.1")
    PORT: int = int(os.getenv("REDIS_PORT", "6379"))
    DB: int = int(os.getenv("REDIS_DB", "1"))
    PASSWORD: Optional[str] = os.getenv("REDIS_PASSWORD", "123456")
    ENABLED: bool = os.getenv("REDIS_ENABLED", "true").lower() == "true"
    
    # 键前缀
    KEY_PREFIX: str = "kbjx"
    
    # 键名模板
    DOC_HASHES_KEY: str = f"{KEY_PREFIX}:doc:hashes"
    PARA_HASHES_KEY: str = f"{KEY_PREFIX}:para:hashes"
    PARA_SIMHASH_KEY: str = f"{KEY_PREFIX}:para:simhash"
    
    # 连接配置
    SOCKET_CONNECT_TIMEOUT: int = 5
    SOCKET_TIMEOUT: int = 5
    
    # TTL 配置（可选，秒）
    DOC_TTL_DAYS: Optional[int] = None  # 文档级不过期
    PARA_TTL_DAYS: Optional[int] = 90   # 段落级 90 天过期


class TextPipelineConfig:
    """文本管线配置"""
    # 段落处理
    MIN_PARAGRAPH_LEN: int = int(os.getenv("MIN_PARAGRAPH_LEN", "2"))
    
    # 近重复检测
    SIMHASH_DISTANCE_THRESHOLD: int = int(os.getenv("SIMHASH_DISTANCE_THRESHOLD", "3"))
    ENABLE_NEAR_DUPLICATE: bool = os.getenv("ENABLE_NEAR_DUPLICATE", "true").lower() == "true"
    
    # 噪声过滤模式（正则表达式）
    NOISE_PATTERNS: list = [
        r'https?://\S+',  # URL
        r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b',  # Email
        r'\b\d{3}[-.\s]?\d{3,4}[-.\s]?\d{4}\b',  # 电话号码
        r'\b[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}\b',  # GUID
        r'\b[0-9a-fA-F]{32,64}\b',  # 哈希串
        r'第\s*\d+\s*页',  # 页码标记
        r'Page\s+\d+',  # 页码标记（英文）
        r'\d{4}[-/]\d{1,2}[-/]\d{1,2}\s+\d{1,2}:\d{2}(:\d{2})?',  # 时间戳
        r'[-=_]{5,}',  # 重复分隔符
        r'Generated by \w+',  # 生成器标记
        r'Printed on \d{4}-\d{2}-\d{2}',  # 打印日期
        r'第\s*\d+\s*行',  # 行号标记（如：第1行、第234行等）
        r'[图片内容',  # 图片内容占位符
    ]
    
    # 自定义噪声模式（可通过环境变量扩展）
       # 自定义噪声模式（可通过环境变量扩展）
    CUSTOM_NOISE_PATTERNS: list = [
        r'第\s*\d+\s*行',  # 行号标记（如：第1行、第234行等）
        r'【图片内容】',  # 图片内容占位符
        r'\[图片内容[：:]\s*',  # 图片内容标记变体（如：[图片内容: 或 [图片内容：）
        r':[图片内容[：:]\s*',  # 冒号开头的图片内容标记（如：:[图片内容: 或 :[图片内容：）
        r':\s*\[图片识别错误\]\]\s*\|\s*',  # 图片识别错误标记（如：: [图片识别错误]] |）
        r'表格\s*\d+',  # 表格标记（如：表格2、表格123456等）
        r'【图片开始】',  # 图片开始标记
        r'【图片结束】',  # 图片结束标记
        r'\[图片OCR文字\][：:]',  # 图片OCR文字标记（如：[图片OCR文字]: 或 [图片OCR文字]：）
    ]


class StorageConfig:
    """存储配置"""
    BASE_DIR: str = os.getenv("STORAGE_BASE_DIR", "storage")
    ORIGINAL_DIR: str = os.path.join(BASE_DIR, "original")
    CONVERTED_DIR: str = os.path.join(BASE_DIR, "converted")
    BATCH_DIR: str = os.path.join(BASE_DIR, "batch")
    
    # 清理配置
    CLEAN_KEEP_DAYS: int = int(os.getenv("STORAGE_CLEAN_KEEP_DAYS", "0"))


class BatchProcessConfig:
    """批量处理配置"""
    MAX_CONCURRENT_TASKS: int = int(os.getenv("MAX_CONCURRENT_TASKS", "5"))
    TASK_TIMEOUT_SECONDS: int = int(os.getenv("TASK_TIMEOUT_SECONDS", "3600"))


class ConversionConfig:
    """文档转换配置"""
    # 转换后端优先级: libreoffice, word, auto
    # auto = 优先 LibreOffice，失败时尝试 Word
    BACKEND: str = os.getenv("CONVERSION_BACKEND", "auto")
    
    # LibreOffice 可执行文件路径（自动检测或手动指定）
    LIBREOFFICE_PATH: str = os.getenv("LIBREOFFICE_PATH", "")
    
    # LibreOffice 常见安装路径（Windows）
    LIBREOFFICE_DEFAULT_PATHS: list = [
        r"C:\Program Files\LibreOffice\program\soffice.exe",
        r"C:\Program Files (x86)\LibreOffice\program\soffice.exe",
        r"C:\Program Files\LibreOffice 7\program\soffice.exe",
        r"C:\Program Files (x86)\LibreOffice 7\program\soffice.exe",
    ]
    
    # 转换超时时间（秒）
    CONVERSION_TIMEOUT: int = int(os.getenv("CONVERSION_TIMEOUT", "60"))
    
    # 是否跳过临时锁文件（~$ 开头）
    SKIP_TEMP_FILES: bool = os.getenv("SKIP_TEMP_FILES", "true").lower() == "true"


class LogConfig:
    """日志配置"""
    LOG_DIR: str = os.getenv("LOG_DIR", "logs")
    LOG_LEVEL: str = os.getenv("LOG_LEVEL", "INFO")
    
    # 日志轮转
    MAX_BYTES: int = 10 * 1024 * 1024  # 10MB
    BACKUP_COUNT: int = 5
    
    # 日志格式
    CONSOLE_FORMAT: str = "%(asctime)s | %(levelname)-8s | %(message)s"
    FILE_FORMAT: str = "%(asctime)s | %(levelname)-8s | %(name)s | %(filename)s:%(lineno)d | %(funcName)s | %(message)s"


class AppConfig:
    """应用配置"""
    # 服务器配置
    HOST: str = os.getenv("APP_HOST", "0.0.0.0")
    PORT: int = int(os.getenv("APP_PORT", "8000"))
    DEBUG: bool = os.getenv("APP_DEBUG", "false").lower() == "true"
    
    # API 配置
    API_PREFIX: str = "/api/v1"
    
    # CORS 配置
    ALLOW_ORIGINS: list = ["*"]
    ALLOW_CREDENTIALS: bool = True
    ALLOW_METHODS: list = ["*"]
    ALLOW_HEADERS: list = ["*"]


class Config:
    """全局配置类 - 统一访问入口"""
    Redis = RedisConfig
    TextPipeline = TextPipelineConfig
    Storage = StorageConfig
    BatchProcess = BatchProcessConfig
    Conversion = ConversionConfig
    Log = LogConfig
    App = AppConfig
    
    @classmethod
    def get_redis_config(cls) -> dict:
        """获取 Redis 连接配置字典"""
        return {
            "host": cls.Redis.HOST,
            "port": cls.Redis.PORT,
            "db": cls.Redis.DB,
            "password": cls.Redis.PASSWORD
        }
    
    @classmethod
    def validate(cls) -> bool:
        """验证配置的有效性"""
        errors = []
        
        # 验证 Redis 配置
        if cls.Redis.ENABLED:
            if not cls.Redis.HOST:
                errors.append("Redis HOST 不能为空")
            if cls.Redis.PORT < 1 or cls.Redis.PORT > 65535:
                errors.append(f"Redis PORT 无效: {cls.Redis.PORT}")
        
        # 验证文本管线配置
        if cls.TextPipeline.MIN_PARAGRAPH_LEN < 1:
            errors.append(f"MIN_PARAGRAPH_LEN 必须 >= 1: {cls.TextPipeline.MIN_PARAGRAPH_LEN}")
        
        if cls.TextPipeline.SIMHASH_DISTANCE_THRESHOLD < 0:
            errors.append(f"SIMHASH_DISTANCE_THRESHOLD 必须 >= 0: {cls.TextPipeline.SIMHASH_DISTANCE_THRESHOLD}")
        
        # 验证批量处理配置
        if cls.BatchProcess.MAX_CONCURRENT_TASKS < 1:
            errors.append(f"MAX_CONCURRENT_TASKS 必须 >= 1: {cls.BatchProcess.MAX_CONCURRENT_TASKS}")
        
        if errors:
            for error in errors:
                print(f"[配置错误] {error}")
            return False
        
        return True
    
    @classmethod
    def print_config(cls):
        """打印当前配置（调试用）"""
        print("=" * 60)
        print("系统配置")
        print("=" * 60)
        
        print("\n[Redis 配置]")
        print(f"  启用: {cls.Redis.ENABLED}")
        print(f"  地址: {cls.Redis.HOST}:{cls.Redis.PORT}/{cls.Redis.DB}")
        print(f"  密码: {'*' * len(cls.Redis.PASSWORD) if cls.Redis.PASSWORD else '无'}")
        print(f"  键前缀: {cls.Redis.KEY_PREFIX}")
        
        print("\n[文本管线配置]")
        print(f"  最小段落长度: {cls.TextPipeline.MIN_PARAGRAPH_LEN}")
        print(f"  SimHash 距离阈值: {cls.TextPipeline.SIMHASH_DISTANCE_THRESHOLD}")
        print(f"  启用近重复检测: {cls.TextPipeline.ENABLE_NEAR_DUPLICATE}")
        print(f"  噪声模式数: {len(cls.TextPipeline.NOISE_PATTERNS)}")
        
        print("\n[存储配置]")
        print(f"  基础目录: {cls.Storage.BASE_DIR}")
        print(f"  清理保留天数: {cls.Storage.CLEAN_KEEP_DAYS}")
        
        print("\n[批量处理配置]")
        print(f"  最大并发数: {cls.BatchProcess.MAX_CONCURRENT_TASKS}")
        print(f"  超时时间: {cls.BatchProcess.TASK_TIMEOUT_SECONDS}s")
        
        print("\n[文档转换配置]")
        print(f"  转换后端: {cls.Conversion.BACKEND}")
        print(f"  LibreOffice 路径: {cls.Conversion.LIBREOFFICE_PATH or '自动检测'}")
        print(f"  转换超时: {cls.Conversion.CONVERSION_TIMEOUT}s")
        print(f"  跳过临时文件: {cls.Conversion.SKIP_TEMP_FILES}")
        
        print("\n[日志配置]")
        print(f"  日志目录: {cls.Log.LOG_DIR}")
        print(f"  日志级别: {cls.Log.LOG_LEVEL}")
        print(f"  日志轮转: {cls.Log.MAX_BYTES // 1024 // 1024}MB x {cls.Log.BACKUP_COUNT}")
        
        print("\n[应用配置]")
        print(f"  监听地址: {cls.App.HOST}:{cls.App.PORT}")
        print(f"  调试模式: {cls.App.DEBUG}")
        print(f"  API 前缀: {cls.App.API_PREFIX}")
        
        print("=" * 60)


# 导出配置实例
config = Config


if __name__ == "__main__":
    # 验证配置
    if config.validate():
        print("✓ 配置验证通过\n")
        config.print_config()
    else:
        print("✗ 配置验证失败")
